language: java
before_script:
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS=-Xmx512m"
script: "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && mvn -e clean deploy --settings settings.xml || mvn -e clean verify --settings settings.xml"
jdk:
  - oraclejdk8
branches:
  only:
    - master

sudo: false
after_success:
  - mvn scoverage:report coveralls:report